version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: mrp-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mediareview
      POSTGRES_USER: media
      POSTGRES_PASSWORD: media
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
